services:
  db:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: talkflow-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017
      - DBNAME=talkflow
      - JWT_SECRET=c92fe4842227794cec37a3c1f5d8bd9c044523ca7a6aa7abfad64b4ecabee9fc