services:
  app:
    image: ghcr.io/liueic/talkflow:latest
    container_name: talkflow
    ports:
      - "8080:8080"
    volumes:
      - ./talkflow:/app
    restart: unless-stopped
    networks:
      - talkflow-network
    depends_on:
      - db
    environment:
      - DBNAME=talkflow
      - JWT_SECRET=c92fe4842227794cec37a3c1f5d8bd9c044523ca7a6aa7abfad64b4ecabee9fc